"""Abstract base scraper and normalization framework for APIx Ingestion.

Provides rate limiting, exponential backoff retry logic, robust string/fare/datetime
normalizers, and schema validation adhering to both Backend API and Database models.
"""

from __future__ import annotations

import abc
import hashlib
import logging
import random
import re
import time
from dataclasses import asdict, dataclass, field
from datetime import date, datetime, timezone
from typing import Any, Callable, Dict, List, Optional, Set, Tuple, TypeVar, Union

from ingestion.config import (
    AIRLINE_MAP,
    BOOKING_WINDOW_MAP,
    BookingWindow,
    DEFAULT_ROUTES,
    IngestionConfig,
    Route,
    VALID_AIRLINE_CODES,
    VALID_IATA_CODES,
)

logger = logging.getLogger("ingestion.base")
T = TypeVar("T")


@dataclass
class RawFareRecord:
    """Canonical raw fare record generated by scrapers and synthetic crawlers."""

    airline_code: str  # 2-char IATA code (e.g. 6E, AI)
    flight_number: str  # Full flight designator (e.g. 6E-205)
    origin: str  # 3-char IATA code (e.g. DEL)
    destination: str  # 3-char IATA code (e.g. BOM)
    departure_datetime: str  # ISO 8601: YYYY-MM-DDTHH:MM:SS
    arrival_datetime: str  # ISO 8601: YYYY-MM-DDTHH:MM:SS
    booking_datetime: str  # ISO 8601: YYYY-MM-DDTHH:MM:SS (scraped_at / capture time)
    fare_inr: float  # Total fare in Indian Rupees (INR)
    cabin_class: str = "economy"
    stops: int = 0
    source: str = "synthetic"  # "synthetic", "easemytrip", "makemytrip", etc.
    booking_window: Optional[str] = None  # "T+1", "T+7", "T+15", "T+30"
    flight_date: Optional[str] = None  # YYYY-MM-DD
    duration_minutes: Optional[int] = None
    base_fare: Optional[float] = None
    taxes_and_fees: Optional[float] = None
    total_fare: Optional[float] = None
    is_synthetic: bool = False
    source_platform: Optional[str] = None

    def __post_init__(self) -> None:
        # Align secondary / compatibility fields
        if self.flight_date is None and self.departure_datetime:
            self.flight_date = self.departure_datetime.split("T")[0]
        if self.total_fare is None:
            self.total_fare = self.fare_inr
        if self.source_platform is None:
            self.source_platform = self.source
        if self.base_fare is None:
            # DGCA standard breakdown: approx 78% base fare, 22% taxes/UDF/PSF
            self.base_fare = round(self.fare_inr * 0.78, 2)
            self.taxes_and_fees = round(self.fare_inr - self.base_fare, 2)

    @property
    def origin_iata(self) -> str:
        return self.origin

    @property
    def destination_iata(self) -> str:
        return self.destination

    def generate_dedup_hash(self) -> str:
        """Generates a deterministic hash for deduplication across platforms."""
        key = (
            f"{self.airline_code}:{self.flight_number}:{self.origin}:"
            f"{self.destination}:{self.departure_datetime}:{self.booking_window}"
        )
        return hashlib.sha256(key.encode("utf-8")).hexdigest()

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict with both API and DB-compatible keys."""
        data = asdict(self)
        data["origin_iata"] = self.origin
        data["destination_iata"] = self.destination
        data["hash_id"] = self.generate_dedup_hash()
        return data


@dataclass
class ScrapeResult:
    """Encapsulates the outcome of a scrape operation."""

    source: str
    success: bool
    records: List[RawFareRecord] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    duration_ms: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseScraper(abc.ABC):
    """Abstract Base Class for all airfare scrapers and generators."""

    def __init__(self, config: Optional[IngestionConfig] = None) -> None:
        self.config = config or IngestionConfig()

    def robots_policy(self) -> "RobotsPolicy":
        """Policy for this scraper's origin, resolved once per agent per config."""
        from ingestion.robots import cached_policy

        base_url = getattr(self, "BASE_URL", "") or ""
        return cached_policy(base_url, self.config, self.config.robots_user_agent)

    def robots_gate(self, url: str) -> Optional[str]:
        """Authorise one request against the origin's robots.txt.

        Returns a denial reason when the request must not be made, otherwise None
        after honouring the effective crawl delay. Living on the base class means a
        new crawler cannot accidentally skip the check.
        """
        if not self.config.respect_robots_txt:
            return None
        policy = self.robots_policy()
        if policy.is_deny_all:
            return f"robots.txt unavailable ({policy.denial_reason})"
        if not policy.can_fetch(url, self.config.robots_user_agent):
            return f"robots.txt disallows {url}"
        delay = policy.effective_delay(self.config, self.config.robots_user_agent)
        if delay > 0:
            time.sleep(delay)
        return None

    def rate_limit_delay(self) -> None:
        """Applies configured sleep with randomized jitter to prevent anti-bot blocks."""
        delay = self.config.rate_limit_delay_seconds
        jitter = random.uniform(0.0, self.config.rate_limit_jitter_seconds)
        total_delay = delay + jitter
        logger.debug("Applying rate limit delay of %.2fs", total_delay)
        time.sleep(total_delay)

    def retry_with_backoff(
        self,
        operation: Callable[[], T],
        max_retries: Optional[int] = None,
        backoff_factor: Optional[float] = None,
        exceptions: Tuple[type, ...] = (Exception,),
    ) -> T:
        """Executes an operation with exponential backoff and jitter."""
        retries = max_retries if max_retries is not None else self.config.max_retries
        factor = backoff_factor if backoff_factor is not None else self.config.retry_backoff_factor

        for attempt in range(1, retries + 1):
            try:
                return operation()
            except exceptions as exc:
                if attempt == retries:
                    logger.error("Operation failed after %d attempts: %s", attempt, exc)
                    raise
                wait_time = (factor ** (attempt - 1)) + random.uniform(0.1, 0.5)
                logger.warning(
                    "Attempt %d/%d failed with %s; retrying in %.2fs...",
                    attempt,
                    retries,
                    exc,
                    wait_time,
                )
                time.sleep(wait_time)
        raise RuntimeError("Unreachable retry loop exit")

    @staticmethod
    def normalize_iata(code: str) -> str:
        """Normalizes and validates a 3-character airport IATA code."""
        if not code or not isinstance(code, str):
            raise ValueError(f"Invalid IATA code value: {code}")
        normalized = code.strip().upper()
        if len(normalized) != 3 or not normalized.isalpha():
            raise ValueError(f"IATA code must be exactly 3 alphabetic letters: {code}")
        return normalized

    @staticmethod
    def normalize_airline_code(code: str) -> str:
        """Normalizes and validates a 2-character airline IATA code."""
        if not code or not isinstance(code, str):
            raise ValueError(f"Invalid airline code value: {code}")
        normalized = code.strip().upper()
        if len(normalized) != 2 or not normalized.isalnum():
            raise ValueError(f"Airline code must be 2 alphanumeric characters: {code}")
        return normalized

    @staticmethod
    def normalize_fare(fare_val: Any) -> float:
        """Extracts and normalizes numeric fare amount in INR.

        Handles currency symbols (₹, Rs, INR), commas, and string formatting.
        Raises ValueError if fare is null, non-positive, or unparseable.
        """
        if fare_val is None:
            raise ValueError("Fare cannot be None / null")

        if isinstance(fare_val, (int, float)):
            fare = float(fare_val)
        elif isinstance(fare_val, str):
            match = re.search(r"(\d[\d,]*(?:\.\d+)?)", fare_val)
            if not match:
                raise ValueError(f"Unable to parse fare from string: {fare_val}")
            cleaned = match.group(1).replace(",", "")
            fare = float(cleaned)
        else:
            raise ValueError(f"Unsupported fare type: {type(fare_val)}")

        if fare <= 0:
            raise ValueError(f"Fare must be strictly positive: {fare}")
        return round(fare, 2)

    @staticmethod
    def normalize_datetime(dt_val: Union[datetime, str]) -> str:
        """Normalizes datetime into canonical ISO 8601 string (YYYY-MM-DDTHH:MM:SS)."""
        if isinstance(dt_val, datetime):
            return dt_val.strftime("%Y-%m-%dT%H:%M:%S")
        if isinstance(dt_val, str):
            # Parse and reformat to ensure standardization
            dt_str = dt_val.strip().replace("Z", "")
            # Attempt parsing standard formats
            for fmt in ("%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S", "%Y-%m-%d"):
                try:
                    parsed = datetime.strptime(dt_str[:19], fmt)
                    return parsed.strftime("%Y-%m-%dT%H:%M:%S")
                except ValueError:
                    continue
            return dt_str
        raise ValueError(f"Unsupported datetime type: {type(dt_val)}")

    def validate_record(
        self,
        record: RawFareRecord,
        allowed_origins: Optional[Set[str]] = None,
        allowed_destinations: Optional[Set[str]] = None,
        allowed_airlines: Optional[Set[str]] = None,
    ) -> Tuple[bool, List[str]]:
        """Validates a RawFareRecord against strict business rules.

        Returns (is_valid, list_of_error_reasons).
        """
        errors: List[str] = []

        # 1. Null / non-positive fare
        if record.fare_inr is None:
            errors.append("Fare is null")
        elif record.fare_inr <= 0:
            errors.append(f"Fare must be positive, got {record.fare_inr}")

        # 2. IATA origin & destination
        try:
            self.normalize_iata(record.origin)
            if allowed_origins and record.origin not in allowed_origins:
                errors.append(f"Origin {record.origin} not in allowed set")
        except ValueError as e:
            errors.append(str(e))

        try:
            self.normalize_iata(record.destination)
            if allowed_destinations and record.destination not in allowed_destinations:
                errors.append(f"Destination {record.destination} not in allowed set")
        except ValueError as e:
            errors.append(str(e))

        if record.origin == record.destination:
            errors.append(f"Origin and destination cannot be identical: {record.origin}")

        # 3. Airline code
        try:
            self.normalize_airline_code(record.airline_code)
            if allowed_airlines and record.airline_code not in allowed_airlines:
                errors.append(f"Airline {record.airline_code} not recognized")
        except ValueError as e:
            errors.append(str(e))

        # 4. Flight numbers
        if not record.flight_number or not record.flight_number.strip():
            errors.append("Flight number is missing")

        # 5. Chronological consistency
        try:
            dep = datetime.fromisoformat(record.departure_datetime)
            arr = datetime.fromisoformat(record.arrival_datetime)
            if arr <= dep:
                errors.append(f"Arrival {record.arrival_datetime} must be after departure {record.departure_datetime}")
        except Exception as e:
            errors.append(f"Invalid timestamp format: {e}")

        return (len(errors) == 0, errors)

    @abc.abstractmethod
    def scrape_route(
        self,
        origin: str,
        destination: str,
        target_date: date,
        window_code: str,
    ) -> ScrapeResult:
        """Scrapes or generates fares for a single route on a target date."""
        raise NotImplementedError

    @abc.abstractmethod
    def scrape_all(
        self,
        routes: Optional[List[Route]] = None,
        windows: Optional[List[BookingWindow]] = None,
    ) -> List[ScrapeResult]:
        """Executes a full scraping/generation cycle across all configured routes and windows."""
        raise NotImplementedError
