"""Contract and Schema Alignment Test Suite for APIx.

Validates end-to-end schema integrity and structural alignment between:
1. Ingestion Layer (RawFareRecord, ScrapeResult, IngestionConfig)
2. Database Layer (RawFare, Route, Airline SQLAlchemy ORM models)
3. Backend API Layer (FastAPI Pydantic v2 schemas for ingestion, indices, and analytics)
4. Quant & Statistical Service Layer (FlightQuote, TukeyBounds)
"""

from __future__ import annotations

from datetime import UTC, date, datetime

import pytest
from pydantic import ValidationError
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

# Database models & seed
from backend.app.db.seed import INITIAL_AIRLINES, INITIAL_ROUTES
from backend.app.models.raw_fare import RawFare as DbRawFare
from backend.app.schemas.analytics import (
    AnomalyAlertItem,
    AnomalyAlertsResponse,
    HeatmapCell,
    HeatmapMatrixResponse,
    LeadTimeCurvePoint,
    LeadTimeCurveResponse,
    SectorHeatmapCell,
    SectorHeatmapResponse,
    SectorHeatmapRow,
)
from backend.app.schemas.index import (
    NationalIndexLatestResponse,
    RouteListResponse,
    RouteOverviewItem,
)

# Backend schemas
from backend.app.schemas.ingestion import (
    IngestionBatchRequest,
    IngestionBatchResponse,
)
from backend.app.schemas.ingestion import (
    RawFareRecord as ApiRawFareRecord,
)

# Quant models
from backend.app.services.index_engine import (
    DEFAULT_AIRLINE_MARKET_SHARES,
    DEFAULT_BOOKING_WINDOW_WEIGHTS,
    DEFAULT_DGCA_ROUTE_TRAFFIC_SHARES,
    FlightQuote,
    deduplicate_quotes,
)

# Ingestion models & config
from ingestion.base import RawFareRecord as IngestionRawFareRecord
from ingestion.config import (
    AIRLINES,
    BOOKING_WINDOWS,
    DEFAULT_ROUTES,
)

# ===========================================================================
# 1. Ingestion -> API Schema Alignment
# ===========================================================================


class TestIngestionToApiContract:
    """Validates that records generated by Ingestion conform to API Pydantic schemas."""

    def test_ingestion_record_converts_to_api_record(
        self, sample_ingestion_record: IngestionRawFareRecord
    ) -> None:
        """Every field generated by Ingestion must hydrate an API RawFareRecord."""
        data_dict = sample_ingestion_record.to_dict()

        # Ensure datetime conversion or ISO parsing works seamlessly
        api_record = ApiRawFareRecord(
            airline_code=data_dict["airline_code"],
            flight_number=data_dict["flight_number"],
            origin=data_dict["origin"],
            destination=data_dict["destination"],
            departure_datetime=datetime.fromisoformat(data_dict["departure_datetime"]),
            arrival_datetime=(
                datetime.fromisoformat(data_dict["arrival_datetime"])
                if data_dict.get("arrival_datetime")
                else None
            ),
            booking_datetime=datetime.fromisoformat(data_dict["booking_datetime"]),
            fare_inr=data_dict["fare_inr"],
            cabin_class=data_dict.get("cabin_class", "economy"),
            stops=data_dict.get("stops", 0),
            source=data_dict.get("source", "synthetic"),
            booking_window=7,  # parsed window integer days
        )

        assert api_record.airline_code == sample_ingestion_record.airline_code.upper()
        assert api_record.origin == sample_ingestion_record.origin.upper()
        assert api_record.destination == sample_ingestion_record.destination.upper()
        assert api_record.fare_inr == sample_ingestion_record.fare_inr
        assert api_record.cabin_class == "economy"

    def test_api_record_validates_airport_codes(self) -> None:
        """Airport codes must strictly be 3-letter uppercase IATA codes."""
        # Valid cases (lowercase should be normalized to uppercase)
        rec = ApiRawFareRecord(
            airline_code="6E",
            flight_number="6E-101",
            origin="del",
            destination="bom",
            departure_datetime=datetime(2026, 10, 1, 8, 0),
            booking_datetime=datetime(2026, 9, 24, 6, 0),
            fare_inr=5000.0,
        )
        assert rec.origin == "DEL"
        assert rec.destination == "BOM"

        # Invalid cases: not 3 letters
        with pytest.raises(ValidationError):
            ApiRawFareRecord(
                airline_code="6E",
                flight_number="6E-101",
                origin="DELHI",
                destination="BOM",
                departure_datetime=datetime(2026, 10, 1, 8, 0),
                booking_datetime=datetime(2026, 9, 24, 6, 0),
                fare_inr=5000.0,
            )

        with pytest.raises(ValidationError):
            ApiRawFareRecord(
                airline_code="6E",
                flight_number="6E-101",
                origin="DE",
                destination="BOM",
                departure_datetime=datetime(2026, 10, 1, 8, 0),
                booking_datetime=datetime(2026, 9, 24, 6, 0),
                fare_inr=5000.0,
            )

    def test_api_record_rejects_non_positive_fare(self) -> None:
        """Fare amounts in INR must be strictly positive (> 0)."""
        with pytest.raises(ValidationError):
            ApiRawFareRecord(
                airline_code="6E",
                flight_number="6E-101",
                origin="DEL",
                destination="BOM",
                departure_datetime=datetime(2026, 10, 1, 8, 0),
                booking_datetime=datetime(2026, 9, 24, 6, 0),
                fare_inr=0.0,
            )

        with pytest.raises(ValidationError):
            ApiRawFareRecord(
                airline_code="6E",
                flight_number="6E-101",
                origin="DEL",
                destination="BOM",
                departure_datetime=datetime(2026, 10, 1, 8, 0),
                booking_datetime=datetime(2026, 9, 24, 6, 0),
                fare_inr=-2500.0,
            )

    def test_api_record_fare_components_validation(self) -> None:
        """ApiRawFareRecord validates base_fare and taxes_and_fees as non-negative floats."""
        rec = ApiRawFareRecord(
            airline_code="6E",
            flight_number="6E-101",
            origin="DEL",
            destination="BOM",
            departure_datetime=datetime(2026, 10, 1, 8, 0),
            booking_datetime=datetime(2026, 9, 24, 6, 0),
            fare_inr=5000.0,
            base_fare=3800.0,
            taxes_and_fees=1200.0,
        )
        assert rec.base_fare == 3800.0
        assert rec.taxes_and_fees == 1200.0

        # Reject negative base_fare
        with pytest.raises(ValidationError):
            ApiRawFareRecord(
                airline_code="6E",
                flight_number="6E-101",
                origin="DEL",
                destination="BOM",
                departure_datetime=datetime(2026, 10, 1, 8, 0),
                booking_datetime=datetime(2026, 9, 24, 6, 0),
                fare_inr=5000.0,
                base_fare=-100.0,
            )

        # Reject negative taxes_and_fees
        with pytest.raises(ValidationError):
            ApiRawFareRecord(
                airline_code="6E",
                flight_number="6E-101",
                origin="DEL",
                destination="BOM",
                departure_datetime=datetime(2026, 10, 1, 8, 0),
                booking_datetime=datetime(2026, 9, 24, 6, 0),
                fare_inr=5000.0,
                taxes_and_fees=-50.0,
            )

    def test_ingestion_batch_request_validation(
        self, sample_api_record: ApiRawFareRecord
    ) -> None:
        """Batch ingestion request schema enforces non-empty records list."""
        batch = IngestionBatchRequest(
            batch_id="batch-uuid-test-99",
            source="easemytrip_scraper",
            scraped_at=datetime.now(UTC),
            records=[sample_api_record],
        )
        assert len(batch.records) == 1
        assert batch.source == "easemytrip_scraper"

        # Reject empty records list
        with pytest.raises(ValidationError):
            IngestionBatchRequest(
                batch_id="empty-batch",
                source="test",
                records=[],
            )

    def test_ingestion_batch_response_contract(self) -> None:
        """IngestionBatchResponse schema conforms to required contract fields."""
        resp = IngestionBatchResponse(
            batch_id="batch-123",
            status="success",
            records_received=100,
            records_valid=98,
            errors=["2 records skipped due to null departure_time"],
            message="Batch processed successfully with 2 warnings",
        )
        assert resp.batch_id == "batch-123"
        assert resp.status == "success"
        assert resp.records_received == 100
        assert resp.records_valid == 98
        assert len(resp.errors) == 1


# ===========================================================================
# 2. Ingestion/API -> Database Model Alignment
# ===========================================================================


class TestIngestionToDatabaseContract:
    """Validates data flow and type compatibility between Ingestion/API and SQLAlchemy models."""

    def test_raw_fare_orm_creation_and_persistence(
        self,
        db_session: Session,
        sample_ingestion_record: IngestionRawFareRecord,
    ) -> None:
        """RawFare ORM model can be constructed from ingestion record and persisted."""
        flight_date_obj = date.fromisoformat(
            sample_ingestion_record.flight_date
            or sample_ingestion_record.departure_datetime[:10]
        )
        dep_time = datetime.fromisoformat(
            sample_ingestion_record.departure_datetime
        ).replace(tzinfo=UTC)
        arr_time = (
            datetime.fromisoformat(sample_ingestion_record.arrival_datetime).replace(
                tzinfo=UTC
            )
            if sample_ingestion_record.arrival_datetime
            else None
        )
        booking_time = datetime.fromisoformat(
            sample_ingestion_record.booking_datetime
        ).replace(tzinfo=UTC)

        db_fare = DbRawFare(
            batch_id="batch-test-contract-01",
            origin=sample_ingestion_record.origin,
            destination=sample_ingestion_record.destination,
            flight_date=flight_date_obj,
            booking_window=sample_ingestion_record.booking_window or "T+7",
            airline_code=sample_ingestion_record.airline_code,
            flight_number=sample_ingestion_record.flight_number,
            departure_time=dep_time,
            arrival_time=arr_time,
            duration_minutes=135,
            stops=sample_ingestion_record.stops,
            fare_class="Economy",
            base_fare=sample_ingestion_record.base_fare or 4200.0,
            taxes_and_fees=sample_ingestion_record.taxes_and_fees or 1220.0,
            total_fare=sample_ingestion_record.fare_inr,
            source_platform=sample_ingestion_record.source,
            scraped_at=booking_time,
            hash_id=sample_ingestion_record.generate_dedup_hash(),
            is_synthetic=False,
        )

        db_session.add(db_fare)
        db_session.commit()

        # Query back from DB and verify exact field retention
        retrieved = db_session.query(DbRawFare).filter_by(hash_id=db_fare.hash_id).one()
        assert retrieved.id is not None
        assert retrieved.origin == "DEL"
        assert retrieved.destination == "BOM"
        assert retrieved.total_fare == 5420.0
        assert retrieved.airline_code == "6E"
        assert retrieved.flight_number == "6E-205"
        assert retrieved.booking_window == "T+7"
        assert retrieved.stops == 0

    def test_dedup_hash_uniqueness_constraint_enforced(
        self,
        db_session: Session,
        sample_db_raw_fare: DbRawFare,
    ) -> None:
        """Database enforces unique constraint on hash_id, preventing duplicate quote persistence."""
        db_session.add(sample_db_raw_fare)
        db_session.commit()

        # Attempt to insert identical hash_id
        duplicate_fare = DbRawFare(
            batch_id="batch-duplicate-attempt",
            origin=sample_db_raw_fare.origin,
            destination=sample_db_raw_fare.destination,
            flight_date=sample_db_raw_fare.flight_date,
            booking_window=sample_db_raw_fare.booking_window,
            airline_code=sample_db_raw_fare.airline_code,
            flight_number=sample_db_raw_fare.flight_number,
            total_fare=sample_db_raw_fare.total_fare,
            hash_id=sample_db_raw_fare.hash_id,  # identical hash
            source_platform="another_portal",
        )

        db_session.add(duplicate_fare)
        with pytest.raises(IntegrityError):
            db_session.commit()
        db_session.rollback()

    def test_dedup_hash_reproducibility_across_layers(
        self, sample_ingestion_record: IngestionRawFareRecord
    ) -> None:
        """Hash generation algorithm must be deterministic and exactly 64-char SHA-256."""
        computed_hash = sample_ingestion_record.generate_dedup_hash()
        assert len(computed_hash) == 64
        assert int(computed_hash, 16) > 0  # valid hex number

        # Re-generating for identical input produces the identical hash
        assert sample_ingestion_record.generate_dedup_hash() == computed_hash


# ===========================================================================
# 3. Master Data Alignment: Routes & Airlines
# ===========================================================================


class TestMasterDataAlignment:
    """Validates that routes and airlines match across Ingestion config and Database seeds."""

    def test_route_definitions_match_between_ingestion_and_db_seed(self) -> None:
        """The 14 standard DGCA domestic corridors must exist in both Ingestion and Database seeds."""
        ingestion_route_codes = {r.pair_key for r in DEFAULT_ROUTES}
        db_route_codes = {f"{r['origin']}-{r['destination']}" for r in INITIAL_ROUTES}

        assert len(ingestion_route_codes) == 14
        assert len(db_route_codes) == 14
        assert ingestion_route_codes == db_route_codes

        expected_pairs = {
            "DEL-BOM",
            "BOM-DEL",
            "BLR-DEL",
            "DEL-BLR",
            "BOM-BLR",
            "BLR-BOM",
            "DEL-CCU",
            "CCU-DEL",
            "DEL-HYD",
            "HYD-DEL",
            "DEL-MAA",
            "MAA-DEL",
            "BLR-HYD",
            "HYD-BLR",
        }
        assert ingestion_route_codes == expected_pairs

    def test_dgca_route_weights_sum_to_one(self) -> None:
        """Route traffic weights must sum to 1.000 (100% of monitored basket) in all layers."""
        # 1. Ingestion config route weights
        ingestion_weights_sum = sum(r.dgca_weight for r in DEFAULT_ROUTES)
        assert pytest.approx(ingestion_weights_sum, abs=1e-5) == 1.0

        # 2. Database seed route weights
        db_weights_sum = sum(r["weight"] for r in INITIAL_ROUTES)
        assert pytest.approx(db_weights_sum, abs=1e-5) == 1.0

        # 3. Quant engine default route traffic shares
        quant_weights_sum = sum(DEFAULT_DGCA_ROUTE_TRAFFIC_SHARES.values())
        assert pytest.approx(quant_weights_sum, abs=1e-5) == 1.0

    def test_airline_definitions_match_between_ingestion_and_db_seed(self) -> None:
        """All 5 major domestic carriers match in codes and market share weights."""
        ingestion_airline_codes = {a.code for a in AIRLINES}
        db_airline_codes = {a["code"] for a in INITIAL_AIRLINES}
        quant_airline_codes = set(DEFAULT_AIRLINE_MARKET_SHARES.keys())

        expected_carriers = {"6E", "AI", "IX", "QP", "SG"}
        assert ingestion_airline_codes == expected_carriers
        assert db_airline_codes == expected_carriers
        assert quant_airline_codes == expected_carriers

        # Modelled shares mirroring ingestion.config.AIRLINES, not DGCA figures.
        assert DEFAULT_AIRLINE_MARKET_SHARES["6E"] == 0.60
        assert DEFAULT_AIRLINE_MARKET_SHARES["AI"] == 0.15
        assert DEFAULT_AIRLINE_MARKET_SHARES["IX"] == 0.10
        assert DEFAULT_AIRLINE_MARKET_SHARES["QP"] == 0.10
        assert DEFAULT_AIRLINE_MARKET_SHARES["SG"] == 0.05

        # Database seed INITIAL_AIRLINES must mirror this at 100.0% sum
        db_airline_shares = {a["code"]: a["market_share_pct"] for a in INITIAL_AIRLINES}
        assert db_airline_shares["6E"] == 60.0
        assert db_airline_shares["AI"] == 15.0
        assert db_airline_shares["IX"] == 10.0
        assert db_airline_shares["QP"] == 10.0
        assert db_airline_shares["SG"] == 5.0
        assert pytest.approx(sum(db_airline_shares.values()), abs=1e-9) == 100.0

        # These previously summed to 0.99, which under-weighted every carrier.
        total_market_share = sum(DEFAULT_AIRLINE_MARKET_SHARES.values())
        assert pytest.approx(total_market_share, abs=1e-9) == 1.0

        # Seed market shares must sum to 100% and match
        db_seed_sum = sum(a["market_share_pct"] for a in INITIAL_AIRLINES)
        assert pytest.approx(db_seed_sum, abs=1e-9) == 100.0
        for a in INITIAL_AIRLINES:
            assert a["market_share_pct"] == pytest.approx(
                DEFAULT_AIRLINE_MARKET_SHARES[a["code"]] * 100.0
            )

    def test_booking_windows_standardization(self) -> None:
        """The 5 standard booking windows (T+1, T+7, T+15, T+30, T+45) match across subsystems."""
        codes = [w.code for w in BOOKING_WINDOWS]
        assert codes == ["T+1", "T+7", "T+15", "T+30", "T+45"]

        days = [w.days_advance for w in BOOKING_WINDOWS]
        assert days == [1, 7, 15, 30, 45]

        # Quant engine weights sum to 1.0
        window_weights_sum = sum(DEFAULT_BOOKING_WINDOW_WEIGHTS.values())
        assert pytest.approx(window_weights_sum, abs=1e-5) == 1.0

        # Index pipeline weights match and contain all 5 windows
        from backend.app.services.index_pipeline import (
            CANONICAL_WINDOWS,
            DEFAULT_WINDOW_WEIGHTS,
        )

        assert set(CANONICAL_WINDOWS) == {"T+1", "T+7", "T+15", "T+30", "T+45"}
        for w in codes:
            assert w in DEFAULT_WINDOW_WEIGHTS
            raw_w = w.replace("+", "")
            assert DEFAULT_WINDOW_WEIGHTS[w] == pytest.approx(
                DEFAULT_BOOKING_WINDOW_WEIGHTS[raw_w]
            )


# ===========================================================================
# 4. Quant Engine & Data Conversion Alignment
# ===========================================================================


class TestQuantEngineContract:
    """Validates contract between raw records and Quant Engine analytical functions."""

    def test_raw_records_convert_to_flight_quotes(
        self, sample_ingestion_record: IngestionRawFareRecord
    ) -> None:
        """RawFareRecord converts cleanly into FlightQuote for index computation."""
        quote = FlightQuote(
            origin=sample_ingestion_record.origin,
            destination=sample_ingestion_record.destination,
            flight_date=sample_ingestion_record.flight_date or "2026-10-01",
            airline_code=sample_ingestion_record.airline_code,
            flight_number=sample_ingestion_record.flight_number,
            departure_time=sample_ingestion_record.departure_datetime[11:16],
            fare=sample_ingestion_record.fare_inr,
        )
        assert quote.airline_code == "6E"
        assert quote.fare == 5420.0
        assert quote.origin == "DEL"
        assert quote.destination == "BOM"

    def test_deduplicate_quotes_selects_lowest_consumer_fare(self) -> None:
        """Cross-platform deduplication selects minimum fare for identical flights."""
        quotes = [
            FlightQuote(
                origin="DEL",
                destination="BOM",
                flight_date="2026-10-01",
                airline_code="6E",
                flight_number="6E-204",
                departure_time="08:00",
                fare=5500.0,  # MakeMyTrip price
            ),
            FlightQuote(
                origin="DEL",
                destination="BOM",
                flight_date="2026-10-01",
                airline_code="6E",
                flight_number="6E-204",
                departure_time="08:00",
                fare=5250.0,  # EaseMyTrip lower promotional fare
            ),
            FlightQuote(
                origin="DEL",
                destination="BOM",
                flight_date="2026-10-01",
                airline_code="6E",
                flight_number="6E-204",
                departure_time="08:00",
                fare=5400.0,  # Airline portal direct
            ),
        ]

        deduped = deduplicate_quotes(quotes)
        assert len(deduped) == 1
        assert deduped[0].fare == 5250.0  # Selected best consumer price

    def test_flight_quote_fare_components_and_splits(self) -> None:
        """FlightQuote preserves base_fare, taxes_and_fees, fees, flight_status, and fare_split_basis."""
        quote = FlightQuote(
            origin="DEL",
            destination="BOM",
            flight_date="2026-10-01",
            airline_code="6E",
            flight_number="6E-205",
            departure_time="08:00",
            fare=5420.0,
            base_fare=4200.0,
            taxes_and_fees=1220.0,
            udf_fee=250.0,
            convenience_fee=150.0,
            flight_status="scheduled",
            fare_split_basis="measured",
        )
        assert quote.base_fare == 4200.0
        assert quote.taxes_and_fees == 1220.0
        assert quote.udf_fee == 250.0
        assert quote.convenience_fee == 150.0
        assert quote.flight_status == "scheduled"
        assert quote.fare_split_basis == "measured"

        d = quote.to_dict()
        assert d["base_fare"] == 4200.0
        assert d["taxes_and_fees"] == 1220.0
        assert d["flight_status"] == "scheduled"
        assert d["fare_split_basis"] == "measured"


# ===========================================================================
# 5. API Response Schemas Serialization & Deserialization
# ===========================================================================


class TestApiResponseSchemas:
    """Validates serialization of API response schemas exposed to Frontend and Regulators."""

    def test_national_index_latest_response_schema(self) -> None:
        """NationalIndexLatestResponse validates correct types and attributes."""
        now = datetime.now(UTC)
        resp = NationalIndexLatestResponse(
            timestamp=now,
            index_value=114.28,
            change_24h=1.85,
            change_7d=3.42,
            sample_size=1250,
            base_period="2026-01-01",
            confidence_interval_lower=112.50,
            confidence_interval_upper=116.06,
            status="published",
        )
        assert resp.index_value == 114.28
        assert resp.sample_size == 1250
        assert resp.status == "published"

    def test_route_list_response_schema(self) -> None:
        """RouteListResponse validates route items list and total count."""
        item = RouteOverviewItem(
            route_code="DEL-BOM",
            origin="DEL",
            destination="BOM",
            current_index=118.5,
            change_24h=2.1,
            avg_fare_inr=5600.0,
            min_fare_inr=4200.0,
            active_flights_tracked=48,
            volatility_score=0.32,
        )
        resp = RouteListResponse(routes=[item], total_routes=1)
        assert resp.total_routes == 1
        assert resp.routes[0].route_code == "DEL-BOM"

    def test_analytics_lead_time_curve_schema(self) -> None:
        """LeadTimeCurveResponse validates lead-time advance purchase curve points."""
        point = LeadTimeCurvePoint(
            days_before_departure=7,
            avg_fare_inr=6800.0,
            median_fare_inr=6500.0,
            p10_fare_inr=5200.0,
            p90_fare_inr=8900.0,
            elasticity_factor=1.25,
        )
        resp = LeadTimeCurveResponse(
            route_code="DEL-BOM",
            curve_points=[point],
            generated_at=datetime.now(UTC),
        )
        assert len(resp.curve_points) == 1
        assert resp.curve_points[0].days_before_departure == 7

    def test_analytics_heatmap_schema(self) -> None:
        """HeatmapMatrixResponse validates 7x24 temporal grid structure."""
        cell = HeatmapCell(
            day_of_week=0,
            hour_of_day=8,
            fare_index=1.20,
            avg_fare_inr=6200.0,
        )
        resp = HeatmapMatrixResponse(
            route_code="DEL-BOM",
            metric="avg_fare",
            matrix=[cell],
            min_val=4000.0,
            max_val=9500.0,
        )
        assert resp.route_code == "DEL-BOM"
        assert len(resp.matrix) == 1
        assert resp.matrix[0].hour_of_day == 8

    def test_anomaly_alerts_response_schema(self) -> None:
        """AnomalyAlertsResponse validates alerts list schema."""
        alert = AnomalyAlertItem(
            id="anom-test-001",
            route_code="DEL-BOM",
            airline_code="6E",
            flight_number="6E-205",
            detected_at=datetime.now(UTC),
            anomaly_type="SURGE",
            severity="CRITICAL",
            observed_fare_inr=15400.0,
            expected_fare_inr=6200.0,
            deviation_percent=148.39,
            status="ACTIVE",
        )
        resp = AnomalyAlertsResponse(alerts=[alert], total_alerts=1)
        assert resp.total_alerts == 1
        assert resp.alerts[0].severity == "CRITICAL"
        assert resp.alerts[0].deviation_percent == 148.39

    def test_sector_heatmap_response_schema(self) -> None:
        """SectorHeatmapResponse validates route sector matrix schema."""
        now = datetime.now(UTC)
        cell = SectorHeatmapCell(
            route_code="DEL-BOM",
            origin="DEL",
            destination="BOM",
            booking_window="T+1",
            days_before_departure=1,
            avg_fare_inr=8500.0,
            median_fare_inr=8400.0,
            min_fare_inr=7900.0,
            max_fare_inr=9200.0,
            sample_size=24,
            fare_index=177.08,
        )
        row = SectorHeatmapRow(
            route_code="DEL-BOM",
            origin="DEL",
            destination="BOM",
            windows={"T+1": 8500.0, "T+30": 4800.0},
            surge_multiplier=1.77,
            base_fare_inr=4800.0,
            urgent_fare_inr=8500.0,
            composite_fare_inr=6200.0,
            sample_size=48,
        )
        resp = SectorHeatmapResponse(
            generated_at=now,
            sectors=[row],
            matrix=[cell],
            windows=["T+1", "T+30"],
            total_routes=1,
            data_available=True,
        )
        assert resp.total_routes == 1
        assert resp.data_available is True
        assert resp.sectors[0].surge_multiplier == 1.77
        assert resp.matrix[0].days_before_departure == 1
