"""Database package for APIx."""

from backend.app.db.ingestion_repo import (
    IngestionRepo,
    bulk_insert_raw_fares,
    cleanup_old_raw_fares,
    compute_dedup_hash,
    count_raw_fares,
    create_scraping_run,
    get_raw_fares,
    get_raw_fares_for_calculation,
    get_scraping_run,
    list_scraping_runs,
    record_scraping_run,
    update_scraping_run,
)
from backend.app.db.telemetry_repo import (
    TelemetryRepo,
    bulk_log_scraper_telemetry,
    calculate_crawler_error_rate,
    calculate_crawler_uptime,
    cleanup_old_telemetry,
    count_scraper_telemetry,
    get_active_healthy_proxies,
    get_crawler_summary,
    get_proxy_health_records,
    get_proxy_latency_stats,
    get_proxy_summary,
    get_scraper_telemetry,
    log_proxy_health,
    log_scraper_telemetry,
    upsert_proxy_health,
)
from backend.app.db.session import (
    Base,
    SessionLocal,
    drop_db,
    engine,
    get_db,
    init_db,
)

__all__ = [
    "Base",
    "SessionLocal",
    "engine",
    "get_db",
    "init_db",
    "drop_db",
    "IngestionRepo",
    "bulk_insert_raw_fares",
    "create_scraping_run",
    "update_scraping_run",
    "record_scraping_run",
    "get_scraping_run",
    "list_scraping_runs",
    "cleanup_old_raw_fares",
    "get_raw_fares",
    "get_raw_fares_for_calculation",
    "count_raw_fares",
    "compute_dedup_hash",
    "TelemetryRepo",
    "log_scraper_telemetry",
    "bulk_log_scraper_telemetry",
    "get_scraper_telemetry",
    "count_scraper_telemetry",
    "calculate_crawler_uptime",
    "calculate_crawler_error_rate",
    "get_crawler_summary",
    "log_proxy_health",
    "upsert_proxy_health",
    "get_proxy_health_records",
    "get_active_healthy_proxies",
    "get_proxy_latency_stats",
    "get_proxy_summary",
    "cleanup_old_telemetry",
]
